#debug: true

server:
  url: localhost
  port: 8080

# base config
appConfig:
  # App Name
  app-name: manasobi-boot
  # System Name
  system-name: manasobi-boot
  # DataSource
  data-source:
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    #driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    initial-size: 5
    max-idle: -1
    max-total: 10
    max-wait-millis: 3000
    slow-query-threshold: 3000
    hibernate:
      hbm2ddlAuto: none
      databaseType: mysql
      implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
  # File Upload
  upload.repository:
    img: /ams_NAS/shinhan_file/img_upload
    sla: /ams_NAS/shinhan_file/sla
  # Log
  log:
    level: ERROR
    slack:
      enabled: false
      web-hook-url:
      channel: error_logs
    database.enabled: true
    admin-url:
  #project base path
  project-base-path:

# Active Profiles :: [local|dev|test|stage|prod]
spring:
  profiles.active: local

  #dataSource
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3307/manasobi?useUnicode=true&charaterEncoding=utf-8
    username: root
    password: admin
    hikari:
      connection-timeout: 60000 #60 sec
      maximum-pool-size: 5 # max 5
#spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
#spring.datasource.hikari.minimum-idle=5
#dataSource.cachePrepStmts=true
#dataSource.prepStmtCacheSize=100
#dataSource.prepStmtCacheSqlLimit=2048
#dataSource.useServerPrepStmts=true

  #jpa
  jpa:
    show-sql: false
    hibernate.implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
        hbm2ddl.auto: none


  # Thymeleaf
  thymeleaf:
    #prefix: classpath:/templates
    mode: HTML
    #cache: false

  http:
    # Multipart
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 8192Mb
      max-request-size: 8192Mb

    # HTTP Encoding
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  # Spring MVC
  mvc:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    dispatch-trace-request: true
    dispatch-options-request: true
    favicon.enabled: false
    ignore-default-model-on-redirect: true
    locale: ko_KR
    throw-exception-if-no-handler-found: false

  # JMX
  jmx.enabled: false

  # H2
  #h2.console.enabled: true
  #h2.console.path: /h2-console

# Security
security.basic.enabled: false

# 전문 관련 설정
msg.exchange.gateway.online:
  ip: 10.200.1.78
  port: 8989
  #ip: localhost
  #port: 9000
  security-corp:
    ip: localhost
    port: 33001
  shbank:
    ip: localhost
    port: 33001

msg.exchange.gateway.batch:
  ip: localhost
  port: 9000
  security-corp:
    ip: localhost
    port: 33001
  shbank:
    ip: localhost
    port: 33001



--- # Profile -------------------- :: local :: --------------------
spring:
  profiles: local
  thymeleaf.cache: false
  #devtools.livereload.enabled: true

appConfig:
  # DataSource
  data-source:
    url: jdbc:log4jdbc:mariadb://localhost:3307/manasobi?useUnicode=true&charaterEncoding=utf-8
    username: root
    password: admin

  #data-source:
    #url: jdbc:oracle:thin:@//10.200.2.16:1531/amsdb
    #username: ams
    #password: aamswc01

# Logging
logging.config: classpath:logback-local.xml


--- # Profile -------------------- :: dev :: --------------------
spring:
  profiles: dev


--- # Profile -------------------- :: test :: --------------------
spring:
  profiles: test

--- # Profile -------------------- :: prod :: --------------------
spring:
  profiles: prod

# Server Config
server:
  url: localhost
  port: 80

# Logging
logging.config: /var/log/logback.xml

