package io.manasobi.core.model.extract.template;

public interface Templates {
    String SINGLE_KEY_ENTITY_CLASS_TEMPLATE = "SINGLE_KEY_ENTITY_CLASS_TEMPLATE";
    String COMPOSITE_KEY_ENTITY_CLASS_TEMPLATE = "COMPOSITE_KEY_ENTITY_CLASS_TEMPLATE";
    String SERVICE_TEMPLATE = "SERVICE_TEMPLATE";
    String REPOSITORY_TEMPLATE = "REPOSITORY_TEMPLATE";
    String VO_TEMPLATE = "VO_TEMPLATE";
    String CONTROLLER_TEMPLATE = "CONTROLLER_TEMPLATE";
    String MYBATIS_INTERFACE_TEMPLATE = "MYBATIS_INTERFACE_TEMPLATE";
    String MYBATIS_XML_TEMPLATE = "MYBATIS_XML_TEMPLATE";
    String VIEW_ROUTER_TEMPLATE = "VIEW_ROUTER_TEMPLATE";
}
